# Notebook 2 for Project 1: _Drugs in Switzerland_

### This is a new dataset that I want to analyze. Unlike previous datasets, the data is spread across multiple Excel sheets, with one sheet for each year from 2009 to 2025. My plan:
#### - Load all sheets at once
#### - Combine them into a single dataset
#### - Clean and rename variables
#### - Explore trends over time
#### - Look for interesting stories in the data
#### - Compare Swiss drug offence trends with European wastewater data (Notebook 1)

In [68]:
import pandas as pd

file = "su-d-19.02.01.02.01_2000.xlsx"

xls = pd.ExcelFile(file)

print(xls.sheet_names)

['2025', '2024', '2023', '2022', '2021', '2020', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2010', '2009']

In [2]:
df_2025 = pd.read_excel(
    file,
    sheet_name="2025",
    header=5
)

df_2025.head(15)

,Straftatbestand,Fälle1,Total,davon Versuche,davon aufgeklärt,Total.1,davon juristische Personen,davon natürliche Personen,männlich,weiblich,...,40 - 49 Jahre,50 - 59 Jahre,60 - 69 Jahre,70 Jahre und +,ohne Angabe.1,Total\nSchweizer/innen,Total\nAusländer/innen,davon ständige ausländische Wohn-bevölkerung,davon Asyl-bevölkerung,davon übrige Ausländer/innen
0,Gesamttotal,27331.0,44228.0,39.0,42490.0,20554.0,5.0,20549.0,17883,2666,...,3581,1585,409,72,1,9007,11542,5604,994,4944
1,Total Straftaten zum Eigenkonsum: illegaler Ko...,24141.0,32378.0,7.0,31672.0,18143.0,2.0,18141.0,15795,2346,...,3193,1385,338,53,1,8197,9944,5056,934,3954
2,Konsum von Betäubungsmitteln,18268.0,19236.0,5.0,19224.0,14705.0,0.0,14705.0,12908,1797,...,2492,1051,234,35,0,6709,7996,4226,745,3025
3,"anbauen, herstellen oder anders erzeugen, zum ...",154.0,162.0,1.0,160.0,158.0,0.0,158.0,138,20,...,43,26,3,2,0,127,31,27,2,2
4,"lagern, versenden, befördern, einführen, ausfü...",1245.0,1257.0,1.0,1198.0,1133.0,0.0,1133.0,875,258,...,231,114,63,14,1,505,628,261,22,345
5,"besitzen, aufbewahren, erwerben oder anders er...",11583.0,11723.0,0.0,11090.0,8829.0,2.0,8827.0,7735,1092,...,1591,722,177,22,1,3885,4942,2297,541,2104
6,Total Straftaten nicht für den persönlichen Ko...,6769.0,11363.0,31.0,10343.0,6100.0,5.0,6095.0,5388,707,...,1029,471,142,25,0,2465,3630,1535,266,1829
7,davon Vergehen,5837.0,8932.0,29.0,7999.0,5086.0,3.0,5083.0,4495,588,...,850,388,118,23,0,2176,2907,1262,249,1396
8,"anbauen, herstellen oder anders erzeugen",235.0,289.0,3.0,279.0,278.0,0.0,278.0,253,25,...,72,28,8,1,0,210,68,57,3,8
9,"lagern, versenden, befördern, einführen, ausfü...",975.0,1008.0,3.0,859.0,858.0,2.0,856.0,700,156,...,154,83,33,9,0,351,505,195,14,296
10,"veräussern, verordnen, andern verschaffen, in ...",2990.0,3361.0,23.0,3265.0,2900.0,1.0,2899.0,2591,308,...,440,198,52,10,0,1212,1687,704,151,832
11,"besitzen, aufbewahren, erwerben, anders erlangen",3995.0,4179.0,0.0,3502.0,3316.0,0.0,3316.0,2978,338,...,573,234,72,16,0,1395,1921,804,175,942
12,illegalen Betäubungsmittelhandel finanzieren o...,17.0,19.0,0.0,19.0,20.0,0.0,20.0,13,7,...,6,0,1,0,0,11,9,9,0,0
13,"öffentlich auffordern, öffentlich Gelegenheit ...",11.0,12.0,0.0,12.0,12.0,0.0,12.0,12,0,...,1,0,0,0,0,1,11,4,2,5
14,Betäubungsmittel einer Person unter 18 Jahren ...,58.0,59.0,0.0,58.0,58.0,0.0,58.0,54,4,...,3,3,0,1,0,29,29,23,5,1

In [3]:
df_2025.shape
df_2025.columns

Index(['Straftatbestand', 'Fälle1', 'Total', 'davon Versuche',
       'davon aufgeklärt', 'Total.1', 'davon juristische Personen',
       'davon natürliche Personen', 'männlich', 'weiblich', 'ohne Angabe',
       '<10 Jahre', '10 - 14 Jahre', '15 - 17 Jahre', '18 - 19 Jahre',
       '20 - 24 Jahre', '25 - 29 Jahre', '30 - 34 Jahre', '35 - 39 Jahre',
       '40 - 49 Jahre', '50 - 59 Jahre', '60 - 69 Jahre', '70 Jahre und +',
       'ohne Angabe.1', 'Total\nSchweizer/innen', 'Total\nAusländer/innen',
       'davon ständige ausländische Wohn-bevölkerung',
       'davon Asyl-bevölkerung', 'davon übrige Ausländer/innen'],
      dtype='str')

In [4]:
df_2025.tail(20)

,Straftatbestand,Fälle1,Total,davon Versuche,davon aufgeklärt,Total.1,davon juristische Personen,davon natürliche Personen,männlich,weiblich,...,40 - 49 Jahre,50 - 59 Jahre,60 - 69 Jahre,70 Jahre und +,ohne Angabe.1,Total\nSchweizer/innen,Total\nAusländer/innen,davon ständige ausländische Wohn-bevölkerung,davon Asyl-bevölkerung,davon übrige Ausländer/innen
18,"lagern, versenden, befördern, einführen, ausfü...",229.0,269.0,0.0,260.0,248.0,0.0,248.0,210,38,...,47,20,4,0,0,56,192,56,5,131
19,"veräussern, verordnen, andern verschaffen, in ...",969.0,1277.0,2.0,1221.0,1109.0,0.0,1109.0,998,111,...,216,90,20,2,0,398,711,322,25,364
20,"besitzen, aufbewahren, erwerben, anders erlangen",725.0,791.0,0.0,769.0,842.0,2.0,840.0,750,90,...,151,66,19,0,0,285,555,203,11,341
21,illegalen Betäubungsmittelhandel finanzieren o...,13.0,15.0,0.0,15.0,15.0,0.0,15.0,13,2,...,2,1,0,0,0,5,10,6,0,4
22,"öffentlich auffordern, öffentlich Gelegenheit ...",7.0,7.0,0.0,7.0,7.0,0.0,7.0,7,0,...,2,0,0,0,0,1,6,2,0,4
23,in Ausbildungsstätten vorwiegend für Jugendlic...,2.0,2.0,0.0,2.0,2.0,0.0,2.0,X,X,...,X,X,X,X,X,X,X,X,X,X
24,übrige Verbrechen Handel (Art. 20),2.0,3.0,0.0,3.0,2.0,0.0,2.0,X,X,...,X,X,X,X,X,X,X,X,X,X
25,Total: übrige Straftaten gegen das BetmG,458.0,487.0,1.0,475.0,409.0,1.0,408.0,367,41,...,71,28,10,1,0,185,223,77,34,112
26,übrige Übertretungen,25.0,34.0,0.0,25.0,24.0,0.0,24.0,17,7,...,6,1,1,0,0,12,12,4,1,7
27,übrige Vergehen,434.0,453.0,1.0,450.0,387.0,1.0,386.0,351,35,...,65,27,9,1,0,174,212,73,33,106
28,X: Entfällt aus Datenschutzgründen (Totalwerte...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1) Unter einem Fall wird die Gesamtheit aller ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,2) Bei der Auflistung einzelner Strafartikel i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,"3) Ständige Wohnbevölkerung: Schweizer/innen, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Stand der Datenbank: 13.02.2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Quelle: BFS - Polizeiliche Kriminalstatistik (...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,© BFS 2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Auskunftsstelle: Bundesamt für Statistik (BFS)...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
import pandas as pd

file = "su-d-19.02.01.02.01_2000.xlsx"

sheets = pd.read_excel(
    file,
    sheet_name=None,
    header=5
)

dfs = []

for year, sheet in sheets.items():

    sheet = sheet.copy()

    # nur echte Datenzeilen
    sheet = sheet[sheet["Total"].notna()]

    # Jahr hinzufügen
    sheet["Year"] = int(year)

    dfs.append(sheet)

df = pd.concat(dfs, ignore_index=True)

In [7]:
df.shape
df.tail(10)

,Straftatbestand,Fälle1,Total,davon Versuche,davon aufgeklärt,Total.1,davon juristische Personen,davon natürliche Personen,männlich,weiblich,...,50 - 59 Jahre,60 - 69 Jahre,70 Jahre und +,ohne Angabe.1,Total\nSchweizer/innen,Total\nAusländer/innen,davon ständige ausländische Wohn-bevölkerung,davon Asyl-bevölkerung,davon übrige Ausländer/innen,Year
328,davon Vergehen,10683.0,13351.0,51.0,13050.0,9606.0,2.0,9604.0,8637.0,967.0,...,230.0,30.0,2.0,1.0,5361.0,4243.0,2017.0,802.0,1424.0,2009
329,"anbauen, herstellen oder anders erzeugen",638.0,707.0,6.0,698.0,684.0,1.0,683.0,619.0,64.0,...,33.0,3.0,0.0,0.0,579.0,104.0,90.0,1.0,13.0,2009
330,"lagern, versenden, befördern, einführen, ausfü...",444.0,480.0,7.0,458.0,438.0,0.0,438.0,359.0,79.0,...,18.0,5.0,0.0,0.0,181.0,257.0,66.0,9.0,182.0,2009
331,"besitzen, aufbewahren, erwerben, anders erlangen",6996.0,7209.0,3.0,7029.0,6355.0,2.0,6353.0,5748.0,605.0,...,153.0,23.0,0.0,0.0,3710.0,2643.0,1334.0,393.0,916.0,2009
332,Ehemalige Kategorie Handel (Vergehen),4619.0,4955.0,35.0,4865.0,4320.0,1.0,4319.0,3911.0,408.0,...,114.0,12.0,2.0,1.0,2124.0,2195.0,945.0,603.0,647.0,2009
333,davon Verbrechen,2405.0,4507.0,7.0,4439.0,2844.0,0.0,2844.0,2506.0,338.0,...,113.0,24.0,6.0,12.0,767.0,2077.0,550.0,304.0,1223.0,2009
334,"anbauen, herstellen oder anders erzeugen",143.0,157.0,0.0,156.0,126.0,0.0,126.0,109.0,17.0,...,12.0,1.0,1.0,0.0,96.0,30.0,26.0,0.0,4.0,2009
335,"lagern, versenden, befördern, einführen, ausfü...",246.0,412.0,2.0,404.0,349.0,0.0,349.0,281.0,68.0,...,20.0,6.0,4.0,10.0,74.0,275.0,65.0,13.0,197.0,2009
336,"besitzen, aufbewahren, erwerben, anders erlangen",1095.0,1219.0,1.0,1191.0,1213.0,0.0,1213.0,1114.0,99.0,...,47.0,6.0,2.0,8.0,270.0,943.0,166.0,151.0,626.0,2009
337,Ehemalige Kategorie Handel (Verbrechen),2040.0,2719.0,4.0,2688.0,2432.0,0.0,2432.0,2153.0,279.0,...,91.0,22.0,3.0,4.0,623.0,1809.0,492.0,290.0,1027.0,2009

In [8]:
df["Year"].unique()

array([2025, 2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015,
       2014, 2013, 2012, 2011, 2010, 2009])

In [9]:
df = df.replace("X", pd.NA)

In [12]:
df_all = df.rename(columns={
    "Straftatbestand": "Offence",
    "Total": "Offences_total",
    "davon Versuche": "Attempts",
    "davon aufgeklärt": "Solved",
    "Total.1": "Suspects_total",
    "davon juristische Personen": "Legal_entities",
    "davon natürliche Personen": "Natural_persons",
    "männlich": "Male",
    "weiblich": "Female",
    "ohne Angabe": "Gender_unknown",
    "<10 Jahre": "Under_10",
    "10 - 14 Jahre": "Age_10_14",
    "15 - 17 Jahre": "Age_15_17",
    "18 - 19 Jahre": "Age_18_19",
    "20 - 24 Jahre": "Age_20_24",
    "25 - 29 Jahre": "Age_25_29",
    "30 - 34 Jahre": "Age_30_34",
    "35 - 39 Jahre": "Age_35_39",
    "40 - 49 Jahre": "Age_40_49",
    "50 - 59 Jahre": "Age_50_59",
    "60 - 69 Jahre": "Age_60_69",
    "70 Jahre und +": "Age_70_plus",
    "ohne Angabe.1": "Age_unknown",
    "Total\nSchweizer/innen": "Swiss",
    "Total\nAusländer/innen": "Foreign",
    "davon ständige ausländische Wohn-bevölkerung": "Foreign_residents",
    "davon Asyl-bevölkerung": "Asylum_population",
    "davon übrige Ausländer/innen": "Other_foreigners"
})

In [13]:
df_all["Offence"] = df_all["Offence"].str.strip()

In [14]:
df_all.info()

<class 'pandas.DataFrame'>
RangeIndex: 338 entries, 0 to 337
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Offence            338 non-null    str
 1   Fälle1             338 non-null    float64
 2   Offences_total     338 non-null    float64
 3   Attempts           338 non-null    float64
 4   Solved             338 non-null    float64
 5   Suspects_total     338 non-null    float64
 6   Legal_entities     338 non-null    float64
 7   Natural_persons    338 non-null    float64
 8   Male               332 non-null    object
 9   Female             332 non-null    object
 10  Gender_unknown     332 non-null    object
 11  Under_10           330 non-null    object
 12  Age_10_14          330 non-null    object
 13  Age_15_17          330 non-null    object
 14  Age_18_19          330 non-null    object
 15  Age_20_24          330 non-null    object
 16  Age_25_29          330 non-null    object
 17  Age_30_34          330 non-null    object
 18  Age_35_39          330 non-null    object
 19  Age_40_49          330 non-null    object
 20  Age_50_59          330 non-null    object
 21  Age_60_69          330 non-null    object
 22  Age_70_plus        330 non-null    object
 23  Age_unknown        330 non-null    object
 24  Swiss              330 non-null    object
 25  Foreign            330 non-null    object
 26  Foreign_residents  320 non-null    object
 27  Asylum_population  320 non-null    object
 28  Other_foreigners   320 non-null    object
 29  Year               338 non-null    int64
dtypes: float64(7), int64(1), object(21), str(1)
memory usage: 79.3+ KB

In [15]:
df_all = df_all.replace("X", pd.NA)

In [16]:
df_all.head()

,Offence,Fälle1,Offences_total,Attempts,Solved,Suspects_total,Legal_entities,Natural_persons,Male,Female,...,Age_50_59,Age_60_69,Age_70_plus,Age_unknown,Swiss,Foreign,Foreign_residents,Asylum_population,Other_foreigners,Year
0,Gesamttotal,27331.0,44228.0,39.0,42490.0,20554.0,5.0,20549.0,17883,2666,...,1585,409,72,1,9007,11542,5604,994,4944,2025
1,Total Straftaten zum Eigenkonsum: illegaler Ko...,24141.0,32378.0,7.0,31672.0,18143.0,2.0,18141.0,15795,2346,...,1385,338,53,1,8197,9944,5056,934,3954,2025
2,Konsum von Betäubungsmitteln,18268.0,19236.0,5.0,19224.0,14705.0,0.0,14705.0,12908,1797,...,1051,234,35,0,6709,7996,4226,745,3025,2025
3,"anbauen, herstellen oder anders erzeugen, zum ...",154.0,162.0,1.0,160.0,158.0,0.0,158.0,138,20,...,26,3,2,0,127,31,27,2,2,2025
4,"lagern, versenden, befördern, einführen, ausfü...",1245.0,1257.0,1.0,1198.0,1133.0,0.0,1133.0,875,258,...,114,63,14,1,505,628,261,22,345,2025

In [17]:
# numerische spalten wirklich numerisch machen... 

cols_to_convert = [
    col for col in df_all.columns
    if col not in ["Offence", "Year"]
]

for col in cols_to_convert:
    df_all[col] = pd.to_numeric(df_all[col], errors="coerce")

In [19]:
df_all.groupby(["Year", "Offence"]).size().sort_values(ascending=False).head(20)

Year  Offence
2024  anbauen, herstellen oder anders erzeugen                                                                  2
      illegalen Betäubungsmittelhandel finanzieren oder Finanzierung vermitteln                                 2
2023  veräussern, verordnen, andern verschaffen, in Verkehr bringen                                             2
2013  lagern, versenden, befördern, einführen, ausführen oder durchführen                                       2
2023  öffentlich auffordern, öffentlich Gelegenheit zu Erwerb oder Konsum von Betäubungsmittel bekannt geben    2
2017  lagern, versenden, befördern, einführen, ausführen oder durchführen                                       2
2013  besitzen, aufbewahren, erwerben, anders erlangen                                                          2
      anbauen, herstellen oder anders erzeugen                                                                  2
2021  öffentlich auffordern, öffentlich Gelegenheit zu Erwerb oder Konsum von Betäubungsmittel bekannt geben    2
      veräussern, verordnen, andern verschaffen, in Verkehr bringen                                             2
2018  anbauen, herstellen oder anders erzeugen                                                                  2
2021  lagern, versenden, befördern, einführen, ausführen oder durchführen                                       2
2012  lagern, versenden, befördern, einführen, ausführen oder durchführen                                       2
2022  illegalen Betäubungsmittelhandel finanzieren oder Finanzierung vermitteln                                 2
2012  besitzen, aufbewahren, erwerben, anders erlangen                                                          2
2018  besitzen, aufbewahren, erwerben, anders erlangen                                                          2
2021  illegalen Betäubungsmittelhandel finanzieren oder Finanzierung vermitteln                                 2
2012  anbauen, herstellen oder anders erzeugen                                                                  2
2024  besitzen, aufbewahren, erwerben, anders erlangen                                                          2
2023  lagern, versenden, befördern, einführen, ausführen oder durchführen                                       2
dtype: int64

In [20]:
df_all.groupby("Year")["Offence"].count()

Year
2009    16
2010    16
2011    16
2012    16
2013    16
2014    16
2015    16
2016    16
2017    16
2018    16
2019    19
2020    19
2021    28
2022    28
2023    28
2024    28
2025    28
Name: Offence, dtype: int64

In [21]:
# das heisst, die kategorien haben sich über die zeit verändert... 

stable = (
    df_all.groupby("Offence")["Year"]
    .nunique()
    .sort_values()
)

stable

Offence
Konsum von Betäubungsmitteln4                                                                                                                 1
Betäubungsmittel einer Person unter 18 Jahren ohne medizinische Indikation, anbieten, abgeben oder anders zugänglich machen                   5
übrige Vergehen                                                                                                                               5
übrige Verbrechen Handel (Art. 20)                                                                                                            5
öffentlich auffordern, öffentlich Gelegenheit zu Erwerb oder Konsum von Betäubungsmittel bekannt geben                                        5
veräussern, verordnen, andern verschaffen, in Verkehr bringen                                                                                 5
Total Straftaten zum Eigenkonsum: illegaler Konsum, Besitz, Kauf, Gebrauch, Anbau oder Herstellung                                            5
in Ausbildungsstätten vorwiegend für Jugendliche gewerbsmässig Betäubungsmittel anbieten, abgeben oder auf andere Weise zugänglich machen     5
illegalen Betäubungsmittelhandel finanzieren oder Finanzierung vermitteln                                                                     5
übrige Vergehen Handel (Art. 20)                                                                                                              5
lagern, versenden, befördern, einführen, ausführen oder durchführen, zum Eigenkonsum                                                          7
übrige Übertretungen                                                                                                                          7
Total: übrige Straftaten gegen das BetmG                                                                                                      7
Total Straftaten zum Eigenkonsum: illegaler Konsum, Besitz, Kauf, Gebrauch, Anbau oder Herstellung4                                          12
Ehemalige Kategorie Handel (Vergehen)                                                                                                        12
Ehemalige Kategorie Handel (Verbrechen)                                                                                                      12
Konsum von Betäubungsmitteln                                                                                                                 16
anbauen, herstellen oder anders erzeugen                                                                                                     17
besitzen, aufbewahren, erwerben, anders erlangen                                                                                             17
davon Verbrechen                                                                                                                             17
davon Vergehen                                                                                                                               17
lagern, versenden, befördern, einführen, ausführen oder durchführen                                                                          17
Total Straftaten nicht für den persönlichen Konsum bestimmt: illegaler Handel, Anbau oder Herstellung                                        17
Gesamttotal                                                                                                                                  17
anbauen, herstellen oder anders erzeugen, zum Eigenkonsum                                                                                    17
besitzen, aufbewahren, erwerben oder anders erlangen, zum Eigenkonsum                                                                        17
Name: Year, dtype: int64

## Diese Delikte kann ich von 2009–2025 sauber analysieren:

Gesamttotal

Konsum von Betäubungsmitteln

anbauen, herstellen oder anders erzeugen

anbauen, herstellen oder anders erzeugen, zum Eigenkonsum

besitzen, aufbewahren, erwerben oder anders erlangen, zum Eigenkonsum

besitzen, aufbewahren, erwerben, anders erlangen

lagern, versenden, befördern, einführen, ausführen oder durchführen

davon Vergehen

davon Verbrechen

In [22]:

# nur Delikte, die über alle 17 Jahre vergleichbar sind.

stable_offences = (
    df_all.groupby("Offence")["Year"]
    .nunique()
)

stable_offences = stable_offences[
    stable_offences == 17
].index

df_stable = df_all[
    df_all["Offence"].isin(stable_offences)
]

In [23]:
df_all = df_all[
    ~df_all["Offence"].str.endswith("4", na=False)
]

In [24]:
df_all["Offence"].unique()

<StringArray>
[                                                                                                                              'Gesamttotal',
                                        'Total Straftaten zum Eigenkonsum: illegaler Konsum, Besitz, Kauf, Gebrauch, Anbau oder Herstellung',
                                                                                                              'Konsum von Betäubungsmitteln',
                                                                                 'anbauen, herstellen oder anders erzeugen, zum Eigenkonsum',
                                                      'lagern, versenden, befördern, einführen, ausführen oder durchführen, zum Eigenkonsum',
                                                                     'besitzen, aufbewahren, erwerben oder anders erlangen, zum Eigenkonsum',
                                     'Total Straftaten nicht für den persönlichen Konsum bestimmt: illegaler Handel, Anbau oder Herstellung',
                                                                                                                            'davon Vergehen',
                                                                                                  'anbauen, herstellen oder anders erzeugen',
                                                                       'lagern, versenden, befördern, einführen, ausführen oder durchführen',
                                                                             'veräussern, verordnen, andern verschaffen, in Verkehr bringen',
                                                                                          'besitzen, aufbewahren, erwerben, anders erlangen',
                                                                 'illegalen Betäubungsmittelhandel finanzieren oder Finanzierung vermitteln',
                                    'öffentlich auffordern, öffentlich Gelegenheit zu Erwerb oder Konsum von Betäubungsmittel bekannt geben',
               'Betäubungsmittel einer Person unter 18 Jahren ohne medizinische Indikation, anbieten, abgeben oder anders zugänglich machen',
                                                                                                          'übrige Vergehen Handel (Art. 20)',
                                                                                                                          'davon Verbrechen',
 'in Ausbildungsstätten vorwiegend für Jugendliche gewerbsmässig Betäubungsmittel anbieten, abgeben oder auf andere Weise zugänglich machen',
                                                                                                        'übrige Verbrechen Handel (Art. 20)',
                                                                                                  'Total: übrige Straftaten gegen das BetmG',
                                                                                                                      'übrige Übertretungen',
                                                                                                                           'übrige Vergehen',
                                                                                                     'Ehemalige Kategorie Handel (Vergehen)',
                                                                                                   'Ehemalige Kategorie Handel (Verbrechen)']
Length: 24, dtype: str

In [25]:
df_all = df_all[
    ~df_all["Offence"].str.startswith("Ehemalige Kategorie", na=False)
]

In [40]:
df_all["Year"] = pd.to_numeric(df_all["Year"])
df_stable["Year"] = pd.to_numeric(df_stable["Year"])

In [41]:
pd.set_option("display.max_colwidth", None)
df_all["Offence"].drop_duplicates().sort_values().tolist()

['Betäubungsmittel einer Person unter 18 Jahren ohne medizinische Indikation, anbieten, abgeben oder anders zugänglich machen',
 'Gesamttotal',
 'Konsum von Betäubungsmitteln',
 'Total Straftaten nicht für den persönlichen Konsum bestimmt: illegaler Handel, Anbau oder Herstellung',
 'Total Straftaten zum Eigenkonsum: illegaler Konsum, Besitz, Kauf, Gebrauch, Anbau oder Herstellung',
 'Total: übrige Straftaten gegen das BetmG',
 'anbauen, herstellen oder anders erzeugen',
 'anbauen, herstellen oder anders erzeugen, zum Eigenkonsum',
 'besitzen, aufbewahren, erwerben oder anders erlangen, zum Eigenkonsum',
 'besitzen, aufbewahren, erwerben, anders erlangen',
 'davon Verbrechen',
 'davon Vergehen',
 'illegalen Betäubungsmittelhandel finanzieren oder Finanzierung vermitteln',
 'in Ausbildungsstätten vorwiegend für Jugendliche gewerbsmässig Betäubungsmittel anbieten, abgeben oder auf andere Weise zugänglich machen',
 'lagern, versenden, befördern, einführen, ausführen oder durchführen',
 'lagern, versenden, befördern, einführen, ausführen oder durchführen, zum Eigenkonsum',
 'veräussern, verordnen, andern verschaffen, in Verkehr bringen',
 'öffentlich auffordern, öffentlich Gelegenheit zu Erwerb oder Konsum von Betäubungsmittel bekannt geben',
 'übrige Verbrechen Handel (Art. 20)',
 'übrige Vergehen',
 'übrige Vergehen Handel (Art. 20)',
 'übrige Übertretungen']

In [42]:
df_all = df_all[
    ~df_all["Offence"].str.endswith("4", na=False)
]

df_all = df_all[
    ~df_all["Offence"].str.startswith("Ehemalige Kategorie", na=False)
]

In [43]:
df_all[
    df_all["Offence"] == "anbauen, herstellen oder anders erzeugen"
][["Year", "Offence", "Offences_total"]]

## we have dublicates..

     Year                                   Offence  Offences_total
8    2025  anbauen, herstellen oder anders erzeugen           289.0
17   2025  anbauen, herstellen oder anders erzeugen            67.0
36   2024  anbauen, herstellen oder anders erzeugen           335.0
45   2024  anbauen, herstellen oder anders erzeugen           125.0
64   2023  anbauen, herstellen oder anders erzeugen           371.0
73   2023  anbauen, herstellen oder anders erzeugen            94.0
92   2022  anbauen, herstellen oder anders erzeugen           434.0
101  2022  anbauen, herstellen oder anders erzeugen            82.0
120  2021  anbauen, herstellen oder anders erzeugen           507.0
129  2021  anbauen, herstellen oder anders erzeugen            97.0
148  2020  anbauen, herstellen oder anders erzeugen           579.0
153  2020  anbauen, herstellen oder anders erzeugen            79.0
167  2019  anbauen, herstellen oder anders erzeugen           509.0
172  2019  anbauen, herstellen oder anders erzeugen            86.0
185  2018  anbauen, herstellen oder anders erzeugen           746.0
190  2018  anbauen, herstellen oder anders erzeugen            80.0
201  2017  anbauen, herstellen oder anders erzeugen           754.0
206  2017  anbauen, herstellen oder anders erzeugen           150.0
217  2016  anbauen, herstellen oder anders erzeugen           798.0
222  2016  anbauen, herstellen oder anders erzeugen           171.0
233  2015  anbauen, herstellen oder anders erzeugen          1650.0
238  2015  anbauen, herstellen oder anders erzeugen           144.0
249  2014  anbauen, herstellen oder anders erzeugen           930.0
254  2014  anbauen, herstellen oder anders erzeugen           187.0
265  2013  anbauen, herstellen oder anders erzeugen           818.0
270  2013  anbauen, herstellen oder anders erzeugen           174.0
281  2012  anbauen, herstellen oder anders erzeugen           769.0
286  2012  anbauen, herstellen oder anders erzeugen           177.0
297  2011  anbauen, herstellen oder anders erzeugen           639.0
302  2011  anbauen, herstellen oder anders erzeugen           131.0
313  2010  anbauen, herstellen oder anders erzeugen           665.0
318  2010  anbauen, herstellen oder anders erzeugen           174.0
329  2009  anbauen, herstellen oder anders erzeugen           707.0
334  2009  anbauen, herstellen oder anders erzeugen           157.0

In [44]:
counts = (
    df_all.groupby(["Year", "Offence"])
    .size()
    .reset_index(name="n")
)

duplicate_offences = counts[counts["n"] > 1]["Offence"].unique()

df_unique = df_all[
    ~df_all["Offence"].isin(duplicate_offences)
].copy()

In [46]:
## Welche Straftaten haben sich wie entwicklet seit 2009? 

latest = (
    df_unique[df_unique["Year"] == 2025]
    [["Offence", "Offences_total"]]
)

oldest = (
    df_unique[df_unique["Year"] == 2009]
    [["Offence", "Offences_total"]]
)

compare = latest.merge(
    oldest,
    on="Offence",
    suffixes=("_2025", "_2009")
)

compare["Change_%"] = (
    (compare["Offences_total_2025"] - compare["Offences_total_2009"])
    / compare["Offences_total_2009"]
) * 100

compare.sort_values("Change_%").round(1)

,Offence,Offences_total_2025,Offences_total_2009,Change_%
2,"anbauen, herstellen oder anders erzeugen, zum Eigenkonsum",162.0,488.0,-66.8
1,Konsum von Betäubungsmitteln,19236.0,43272.0,-55.5
3,"besitzen, aufbewahren, erwerben oder anders erlangen, zum Eigenkonsum",11723.0,24124.0,-51.4
0,Gesamttotal,44228.0,85742.0,-48.4
6,davon Verbrechen,2431.0,4507.0,-46.1
4,"Total Straftaten nicht für den persönlichen Konsum bestimmt: illegaler Handel, Anbau oder Herstellung",11363.0,17858.0,-36.4
5,davon Vergehen,8932.0,13351.0,-33.1

In [47]:
# Der Rückgang scheint vor allem bei Eigenkonsum-Delikten stattzufinden. 
# Nicht unbedingt im selben Ausmass Rückgang beim Handel. Aber auch Rückgang!

In [49]:
compare["Absolute_change"] = (
    compare["Offences_total_2025"]
    - compare["Offences_total_2009"]
)

compare.sort_values("Absolute_change")

,Offence,Offences_total_2025,Offences_total_2009,Change_%,Absolute_change
0,Gesamttotal,44228.0,85742.0,-48.417345,-41514.0
1,Konsum von Betäubungsmitteln,19236.0,43272.0,-55.546312,-24036.0
3,"besitzen, aufbewahren, erwerben oder anders erlangen, zum Eigenkonsum",11723.0,24124.0,-51.405240,-12401.0
4,"Total Straftaten nicht für den persönlichen Konsum bestimmt: illegaler Handel, Anbau oder Herstellung",11363.0,17858.0,-36.370254,-6495.0
5,davon Vergehen,8932.0,13351.0,-33.098644,-4419.0
6,davon Verbrechen,2431.0,4507.0,-46.061682,-2076.0
2,"anbauen, herstellen oder anders erzeugen, zum Eigenkonsum",162.0,488.0,-66.803279,-326.0

In [51]:
total = df_unique[
    df_unique["Offence"] == "Gesamttotal"
]

total[
    [
        "Year",
        "Age_15_17",
        "Age_18_19",
        "Age_20_24",
        "Age_25_29",
        "Age_40_49",
        "Age_50_59"
    ]
].sort_values("Year")

     Year  Age_15_17  Age_18_19  Age_20_24  Age_25_29  Age_40_49  Age_50_59
322  2009     4506.0     4860.0     9516.0     6757.0     3721.0      702.0
306  2010     4352.0     4878.0     9740.0     6960.0     3694.0      783.0
290  2011     4056.0     4789.0     9745.0     6854.0     3714.0      844.0
274  2012     4408.0     5202.0    10169.0     7045.0     3735.0      904.0
258  2013     4741.0     5182.0    10480.0     7291.0     3915.0     1075.0
242  2014     4982.0     3224.0     7293.0     5687.0     3745.0     1113.0
226  2015     5146.0     3129.0     7337.0     5762.0     4067.0     1505.0
210  2016     4996.0     3118.0     7213.0     5630.0     3885.0     1377.0
194  2017     5121.0     2989.0     6989.0     5574.0     3861.0     1571.0
178  2018     4669.0     2915.0     6601.0     5351.0     3817.0     1703.0
159  2019     4468.0     2814.0     6433.0     5192.0     3915.0     1625.0
140  2020     3960.0     2587.0     5537.0     4437.0     3687.0     1722.0
112  2021     2953.0     2237.0     5189.0     4436.0     3624.0     1762.0
84   2022     2482.0     1877.0     4548.0     4023.0     3642.0     1620.0
56   2023     2179.0     1661.0     4088.0     3932.0     3830.0     1551.0
28   2024     1788.0     1314.0     3436.0     3479.0     3785.0     1568.0
0    2025     1400.0     1126.0     3066.0     3287.0     3581.0     1585.0

In [52]:
## Drug-related offences have fallen sharply among young people in Switzerland, while older age groups now account for a growing share of cases.

In [54]:
total["Share_15_17"] = total["Age_15_17"] / total["Suspects_total"] * 100
total["Share_20_24"] = total["Age_20_24"] / total["Suspects_total"] * 100
total["Share_50_59"] = total["Age_50_59"] / total["Suspects_total"] * 100

total[
    ["Year", "Share_15_17", "Share_20_24", "Share_50_59"]
]

     Year  Share_15_17  Share_20_24  Share_50_59
0    2025     6.811326    14.916805     7.711394
28   2024     8.164011    15.688781     7.159490
56   2023     8.987049    16.860513     6.396931
84   2022     9.790927    17.940828     6.390533
112  2021    10.641825    18.699773     6.349778
140  2020    13.284133    18.574304     5.776585
159  2019    13.549248    19.508127     4.927826
178  2018    13.949806    19.722139     5.088139
194  2017    14.822855    20.229825     4.547297
210  2016    14.377392    20.757432     3.962704
226  2015    14.451809    20.604920     4.226578
242  2014    14.702671    21.522798     3.284639
258  2013    11.374760    25.143954     2.579175
274  2012    11.043744    25.477276     2.264869
290  2011    10.697331    25.701551     2.225973
306  2010    11.246350    25.169910     2.023413
322  2009    11.761942    24.839468     1.832420

In [55]:
# Drug offences among teenagers have fallen by nearly 70% in Switzerland since 2009...

In [66]:
age_share[
    ["Year", "Age_15_17", "Age_18_19", "Age_20_24", "Age_50_59"]
].round(1)

     Year  Age_15_17  Age_18_19  Age_20_24  Age_50_59
0    2025        6.8        5.5       14.9        7.7
28   2024        8.2        6.0       15.7        7.2
56   2023        9.0        6.9       16.9        6.4
84   2022        9.8        7.4       17.9        6.4
112  2021       10.6        8.1       18.7        6.3
140  2020       13.3        8.7       18.6        5.8
159  2019       13.5        8.5       19.5        4.9
178  2018       13.9        8.7       19.7        5.1
194  2017       14.8        8.7       20.2        4.5
210  2016       14.4        9.0       20.8        4.0
226  2015       14.5        8.8       20.6        4.2
242  2014       14.7        9.5       21.5        3.3
258  2013       11.4       12.4       25.1        2.6
274  2012       11.0       13.0       25.5        2.3
290  2011       10.7       12.6       25.7        2.2
306  2010       11.2       12.6       25.2        2.0
322  2009       11.8       12.7       24.8        1.8

In [57]:
total = df_unique[
    df_unique["Offence"] == "Gesamttotal"
].copy()

age_chart = total[
    [
        "Year",
        "Age_15_17",
        "Age_18_19",
        "Age_20_24",
        "Age_50_59"
    ]
].sort_values("Year")

age_chart

     Year  Age_15_17  Age_18_19  Age_20_24  Age_50_59
322  2009     4506.0     4860.0     9516.0      702.0
306  2010     4352.0     4878.0     9740.0      783.0
290  2011     4056.0     4789.0     9745.0      844.0
274  2012     4408.0     5202.0    10169.0      904.0
258  2013     4741.0     5182.0    10480.0     1075.0
242  2014     4982.0     3224.0     7293.0     1113.0
226  2015     5146.0     3129.0     7337.0     1505.0
210  2016     4996.0     3118.0     7213.0     1377.0
194  2017     5121.0     2989.0     6989.0     1571.0
178  2018     4669.0     2915.0     6601.0     1703.0
159  2019     4468.0     2814.0     6433.0     1625.0
140  2020     3960.0     2587.0     5537.0     1722.0
112  2021     2953.0     2237.0     5189.0     1762.0
84   2022     2482.0     1877.0     4548.0     1620.0
56   2023     2179.0     1661.0     4088.0     1551.0
28   2024     1788.0     1314.0     3436.0     1568.0
0    2025     1400.0     1126.0     3066.0     1585.0

In [60]:
# for datawrapper

age_chart.to_csv(
    "drug_offences_by_age.csv",
    index=False
)

"A nation of cocaine, but fewer offences"

Die Schweiz gehört bei Kokain weiterhin zur europäischen Spitzengruppe. Gleichzeitig gehen Drogendelikte seit Jahren zurück und die registrierten Täter werden älter. Mehr Kokain im Abwasser bedeutet nicht automatisch mehr registrierte Drogendelikte... 

Switzerland remains among Europe's cocaine hotspots – even as drug offences fall by half.

In [69]:
total_trend = (
    df_unique[
        df_unique["Offence"] == "Gesamttotal"
    ][["Year", "Offences_total"]]
    .sort_values("Year")
)

total_trend

     Year  Offences_total
322  2009         85742.0
306  2010         89173.0
290  2011         91211.0
274  2012         92862.0
258  2013         97289.0
242  2014         80986.0
226  2015         86128.0
210  2016         83268.0
194  2017         80074.0
178  2018         76308.0
159  2019         75757.0
140  2020         68600.0
112  2021         60887.0
84   2022         55304.0
56   2023         54458.0
28   2024         48208.0
0    2025         44228.0

In [71]:
total_trend.to_csv(
    "switzerland_drug_offences_trend.csv",
    index=False
)