# Notebook 1 for Project 1: _Drugs in Switzerland_

#### This project analyzes wastewater data from the European Union Drugs Agency (EUDA).Wastewater analysis provides an indirect measure of drug consumption by detecting drug residues in sewage systems. The dataset covers hundreds of cities across Europe and includes substances such as cocaine, MDMA, amphetamine, cannabis and methamphetamine.

### Key questions:
#### - Which cities and countries report the highest drug loads?
#### - How does Switzerland compare with the rest of Europe?
#### - Which substances are most prevalent?
#### - Do trends in wastewater data align with trends in Swiss drug offence statistics (notebook 2) ?

In [142]:
import pandas as pd

df = pd.read_csv(
    "/Users/aniellepeterhans/Lede/DatasetProject1/ww2026-all-data.csv",
    encoding="cp1252"
)

In [4]:
df.columns

Index(['Year', 'Metabolite', 'Site ID', 'Country', 'City', 'Wednesday',
       'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday',
       'Weekday mean', 'Weekend mean', 'Daily mean'],
      dtype='str')

In [7]:
# Durchschnitt pro Droge und Land
country_drug = (
    df.groupby(["Metabolite", "Country"])["Daily mean"]
      .mean()
      .reset_index()
)

In [8]:
# Pro Droge das Land mit dem höchsten Durchschnitt
top_countries = (
    country_drug.loc[
        country_drug.groupby("Metabolite")["Daily mean"].idxmax()
    ]
    .sort_values("Daily mean", ascending=False)
)

top_countries

          Metabolite Country   Daily mean
175              ets      CA  7987.650000
118          cocaine      CA  1694.810000
171              cot      SE  1288.450000
266  methamphetamine      US   946.826667
84          cannabis      CA   628.980000
69       amphetamine      NO   345.128333
204         ketamine      GB   181.053333
28              MDMA      NL   123.699565

In [9]:
# top 5 Länder pro Droge
country_drug.sort_values(
    ["Metabolite", "Daily mean"],
    ascending=[True, False]
).groupby("Metabolite").head(5)

          Metabolite Country   Daily mean
28              MDMA      NL   123.699565
30              MDMA      NZ    68.115833
22              MDMA      IS    39.574444
3               MDMA      BE    39.039714
21              MDMA      IE    37.745000
69       amphetamine      NO   345.128333
74       amphetamine      SE   318.938529
61       amphetamine      IS   210.182222
59       amphetamine      HU   203.790000
68       amphetamine      NL   175.538333
84          cannabis      CA   628.980000
112         cannabis      US   529.515000
80          cannabis      AU   166.376667
102         cannabis      NL   153.168919
103         cannabis      NO   129.161667
118          cocaine      CA  1694.810000
120          cocaine      CL  1375.977143
129          cocaine      GB   819.503750
134          cocaine      IE   797.435000
117          cocaine      BR   794.085714
171              cot      SE  1288.450000
170              cot      PT  1208.780000
169              cot      PL  1075.140000
157              cot      CZ  1070.262500
168              cot      NO  1036.283333
175              ets      CA  7987.650000
185              ets      PL  7433.030000
176              ets      CZ  6426.197500
181              ets      IE  4034.240000
177              ets      DK  4021.383333
204         ketamine      GB   181.053333
194         ketamine      CA    78.730000
216         ketamine      NL    72.906923
192         ketamine      BE    58.213500
225         ketamine      US    57.535000
266  methamphetamine      US   946.826667
227  methamphetamine      AU   542.260000
235  methamphetamine      CZ   417.952143
231  methamphetamine      CA   230.348333
257  methamphetamine      NZ   203.056667

In [10]:
df["Metabolite"].unique()

<StringArray>
[           'MDMA',     'amphetamine',        'cannabis',         'cocaine',
             'cot',             'ets',        'ketamine', 'methamphetamine']
Length: 8, dtype: str

In [ ]:
# ich habe 8 substanzen

In [11]:
# Durchschnitt pro Substanz und Land berechnen
country_drug = (
    df.groupby(["Metabolite", "Country"])["Daily mean"]
      .mean()
      .reset_index()
)

# Land mit dem höchsten Wert pro Substanz
top_country_per_drug = (
    country_drug.loc[
        country_drug.groupby("Metabolite")["Daily mean"].idxmax()
    ]
    .sort_values("Daily mean", ascending=False)
)

top_country_per_drug

          Metabolite Country   Daily mean
175              ets      CA  7987.650000
118          cocaine      CA  1694.810000
171              cot      SE  1288.450000
266  methamphetamine      US   946.826667
84          cannabis      CA   628.980000
69       amphetamine      NO   345.128333
204         ketamine      GB   181.053333
28              MDMA      NL   123.699565

In [12]:
top_country_per_drug.rename(
    columns={
        "Metabolite": "Drug",
        "Country": "Top Country",
        "Daily mean": "Average Daily Mean"
    }
)

                Drug Top Country  Average Daily Mean
175              ets          CA         7987.650000
118          cocaine          CA         1694.810000
171              cot          SE         1288.450000
266  methamphetamine          US          946.826667
84          cannabis          CA          628.980000
69       amphetamine          NO          345.128333
204         ketamine          GB          181.053333
28              MDMA          NL          123.699565

In [13]:
# doing a data set for Switzerland
switzerland = df[df["Country"] == "CH"]

switzerland.sort_values(
    "Daily mean",
    ascending=False
)[["Metabolite", "City", "Daily mean"]].head(20)

     Metabolite              City  Daily mean
2914    cocaine  St. Gallen Hofen     1336.68
505         cot            Schwyz     1106.92
1299    cocaine            Zurich     1086.39
398     cocaine            Geneva     1076.86
405     cocaine        Zurich (2)     1055.01
1967    cocaine            Zurich     1022.61
500         cot              Chur     1020.66
498         cot        Altenrhein      971.07
401     cocaine            Luzern      948.65
4229    cocaine            Zurich      934.42
2496    cocaine            Zurich      931.09
1298    cocaine            Geneva      917.84
3643    cocaine  St. Gallen Hofen      909.82
400     cocaine            Lugano      895.98
3644    cocaine            Zurich      890.94
507         cot        Zurich (2)      879.90
3281    cocaine            Zurich      874.36
503         cot            Luzern      874.33
3958    cocaine            Zurich      855.96
2493    cocaine             Basel      837.83

In [14]:
# Die höchste Stadt pro Droge in der Schweiz
top_ch_per_drug = (
    switzerland.loc[
        switzerland.groupby("Metabolite")["Daily mean"].idxmax()
    ][["Metabolite", "City", "Daily mean"]]
    .sort_values("Daily mean", ascending=False)
)

top_ch_per_drug

           Metabolite              City  Daily mean
2914          cocaine  St. Gallen Hofen     1336.68
505               cot            Schwyz     1106.92
283          cannabis            Geneva      252.76
2804      amphetamine  St. Gallen Hofen      129.98
4104             MDMA            Zurich       81.20
2993  methamphetamine            Zurich       74.02
1436         ketamine            Zurich       54.30

In [15]:
# Durchschnitt pro Droge für die Schweiz

(
    switzerland.groupby("Metabolite")["Daily mean"]
    .mean()
    .sort_values(ascending=False)
)

Metabolite
cot                850.493000
cocaine            612.916712
cannabis            92.773030
amphetamine         34.235479
MDMA                26.715775
methamphetamine     21.426176
ketamine            20.230000
Name: Daily mean, dtype: float64

In [16]:
# Alle Schweizer Städte nach einer bestimmten Droge
# Kokain:

switzerland = df[
    (df["Country"] == "CH") &
    (df["Metabolite"] == "cocaine")
]

switzerland.sort_values(
    "Daily mean",
    ascending=False
)[["City", "Daily mean"]]

                  City  Daily mean
2914  St. Gallen Hofen     1336.68
1299            Zurich     1086.39
398             Geneva     1076.86
405         Zurich (2)     1055.01
1967            Zurich     1022.61
...                ...         ...
5006             Berne      264.34
4820            Lugano      240.60
4640             Berne      228.93
4643            Lugano      228.49
4639             Basel       42.51

[73 rows x 2 columns]

In [17]:
# Oder MDMA:

switzerland = df[
    (df["Country"] == "CH") &
    (df["Metabolite"] == "MDMA")
]

switzerland.sort_values(
    "Daily mean",
    ascending=False
)[["City", "Daily mean"]]

        City  Daily mean
4104  Zurich       81.20
3779  Zurich       73.40
4350  Zurich       59.32
4735  Zurich       55.42
3462  Zurich       53.66
...      ...         ...
42    Laupen        9.02
41      Chur        8.62
4552  Lugano        7.74
4734  Lugano        3.68
4349  Lugano        2.52

[71 rows x 2 columns]

In [ ]:
# Schweiz-Ranking für jede Droge nach Durchschnitt

In [18]:
country_drug = (
    df.groupby(["Metabolite", "Country"])["Daily mean"]
      .mean()
      .reset_index()
)

# Rang pro Droge
country_drug["Rank"] = (
    country_drug.groupby("Metabolite")["Daily mean"]
    .rank(method="dense", ascending=False)
)

# Nur Schweiz
switzerland_rank = (
    country_drug[country_drug["Country"] == "CH"]
    .sort_values("Rank")
)

switzerland_rank

          Metabolite Country  Daily mean  Rank
119          cocaine      CH  612.916712   8.0
156              cot      CH  850.493000  11.0
232  methamphetamine      CH   21.426176  12.0
85          cannabis      CH   92.773030  13.0
6               MDMA      CH   26.715775  14.0
195         ketamine      CH   20.230000  15.0
46       amphetamine      CH   34.235479  23.0

In [19]:
#Top 15 Länder pro Droge

for drug in df["Metabolite"].unique():
    print(f"\n=== {drug.upper()} ===")

    ranking = (
        country_drug[country_drug["Metabolite"] == drug]
        .sort_values("Daily mean", ascending=False)
        .head(15)
    )

    print(ranking[["Country", "Daily mean"]])

=== MDMA ===
   Country  Daily mean
28      NL  123.699565
30      NZ   68.115833
22      IS   39.574444
3       BE   39.039714
21      IE   37.745000
16      GB   37.687143
39      US   33.920000
1       AU   31.700000
29      NO   30.971667
15      FR   29.887500
20      HU   29.540000
31      PL   28.757143
27      LV   28.541429
6       CH   26.715775
32      PT   26.017429

=== AMPHETAMINE ===
   Country  Daily mean
69      NO  345.128333
74      SE  318.938529
61      IS  210.182222
59      HU  203.790000
68      NL  175.538333
78      US  172.980000
43      BE  142.789437
58      HR  131.873125
45      CA  130.870000
51      EE  110.692500
50      DK  109.272500
66      LV  106.132857
49      DE  104.947677
53      FI   99.220994
41      AU   75.395000

=== CANNABIS ===
    Country  Daily mean
84       CA  628.980000
112      US  529.515000
80       AU  166.376667
102      NL  153.168919
103      NO  129.161667
101      LU  122.237500
92       FR  118.800000
88       DE  117.433750
98       IE  102.245000
107      RS  101.400000
91       ES   99.300000
96       HR   96.217692
85       CH   92.773030
89       DK   92.606667
105      PT   90.721667

=== COCAINE ===
    Country   Daily mean
118      CA  1694.810000
120      CL  1375.977143
129      GB   819.503750
134      IE   797.435000
117      BR   794.085714
153      US   732.056667
142      NL   636.091321
119      CH   612.916712
116      BE   563.376197
126      ES   560.383971
124      DK   454.700000
143      NO   435.275000
135      IS   410.419000
136      IT   359.786000
150      SI   347.853000

=== COT ===
    Country   Daily mean
171      SE  1288.450000
170      PT  1208.780000
169      PL  1075.140000
157      CZ  1070.262500
168      NO  1036.283333
158      DE  1017.566154
163      GR   997.180000
164      HR   946.780000
161      FR   939.800000
159      DK   915.596667
156      CH   850.493000
154      AU   752.030000
160      ES   738.230000
155      CA   717.550000
165      IE   673.380000

=== ETS ===
    Country   Daily mean
175      CA  7987.650000
185      PL  7433.030000
176      CZ  6426.197500
181      IE  4034.240000
177      DK  4021.383333
178      ES  3866.146667
184      NO  3802.963333
174      AU  3484.910000
182      IT  3321.270000
180      HR  3078.310000
187      SE  2733.420000
188      SI  2304.648571
186      PT  1247.310000
179      GR   715.720000
189      TR   572.500000

=== KETAMINE ===
    Country  Daily mean
204      GB  181.053333
194      CA   78.730000
216      NL   72.906923
192      BE   58.213500
225      US   57.535000
209      IE   52.675000
208      HU   39.750000
217      NO   36.418333
203      FR   29.720000
199      DE   25.274333
210      IS   23.615000
193      BR   22.616154
201      ES   22.550000
211      IT   21.304286
195      CH   20.230000

=== METHAMPHETAMINE ===
    Country  Daily mean
266      US  946.826667
227      AU  542.260000
235      CZ  417.952143
231      CA  230.348333
257      NZ  203.056667
264      SK  193.585333
236      DE   92.661944
253      LV   78.797143
265      TR   43.850000
248      IS   25.247778
251      LT   22.950833
232      CH   21.426176
234      CY   21.372500
256      NO   21.226667
247      IE   20.675000

In [ ]:
# Wo liegt die Schweiz im internationalen Vergleich?

In [22]:
country_drug = (
    df.groupby(["Metabolite", "Country"])["Daily mean"]
      .mean()
      .reset_index()
)

for drug in sorted(df["Metabolite"].unique()):
    ranking = (
        country_drug[country_drug["Metabolite"] == drug]
        .sort_values("Daily mean", ascending=False)
        .reset_index(drop=True)
    )

    ch_position = ranking[ranking["Country"] == "CH"].index

    if len(ch_position) > 0:
        print(
            f"{drug}: Platz {ch_position[0]+1} von {len(ranking)} Ländern"
        )

MDMA: Platz 14 von 40 Ländern
amphetamine: Platz 23 von 39 Ländern
cannabis: Platz 13 von 34 Ländern
cocaine: Platz 8 von 41 Ländern
cot: Platz 11 von 20 Ländern
ketamine: Platz 15 von 36 Ländern
methamphetamine: Platz 12 von 41 Ländern

In [ ]:
# Kokain ist krass... cocaine: Platz 8 von 41 Ländern

In [24]:
country_drug = (
    df.groupby(["Metabolite", "Country"])["Daily mean"]
      .mean()
      .reset_index()
)

In [26]:
country_drug

          Metabolite Country  Daily mean
0               MDMA      AT   10.531584
1               MDMA      AU   31.700000
2               MDMA      BA    0.000000
3               MDMA      BE   39.039714
4               MDMA      BR    2.615238
..               ...     ...         ...
262  methamphetamine      SE    5.937742
263  methamphetamine      SI    2.697400
264  methamphetamine      SK  193.585333
265  methamphetamine      TR   43.850000
266  methamphetamine      US  946.826667

[267 rows x 3 columns]

In [103]:
# Die Top-10-Städte Europas für Kokain

cocaine = df[df["Metabolite"] == "cocaine"]

cocaine.sort_values(
    "Daily mean",
    ascending=False
)[["City", "Country", "Daily mean"]].head(20)

                    City Country  Daily mean
393           Whitehorse      CA     5242.54
1301                Lebu      CL     3110.11
449        Middlesbrough      GB     2786.38
1302         Los Angeles      CL     2628.16
2491        Antwerp Zuid      BE     2381.39
1282  Belo Horizonte (2)      BR     2189.65
1287               Natal      BR     2005.30
1280        Antwerp Zuid      BE     1996.98
1953        Antwerp Zuid      BE     1721.58
1300          Concepción      CL     1708.98
2524           Tarragona      ES     1610.55
2909        Antwerp Zuid      BE     1581.88
406              Copiapo      CL     1576.48
1294           Kitchener      CA     1490.15
1335           Tarragona      ES     1482.91
1996           Tarragona      ES     1463.91
448              Bristol      GB     1415.62
440               Lleida      ES     1405.43
376         Antwerp Zuid      BE     1382.14
2914    St. Gallen Hofen      CH     1336.68

In [102]:
# einige Namen waren doppelt... also nicht pro stadt...

cocaine = df[df["Metabolite"] == "cocaine"]

cocaine_city = (
    cocaine.groupby(["City", "Country"], as_index=False)
    .agg(
        daily_mean=("Daily mean", "mean")
    )
)

cocaine_city.sort_values(
    "daily_mean",
    ascending=False
).head(20)

                        City Country   daily_mean
242               Whitehorse      CA  5242.540000
140            Middlesbrough      GB  2786.380000
116                     Lebu      CL  1662.060000
48                   Copiapo      CL  1576.480000
18        Belo Horizonte (2)      BR  1552.150000
223                Tarragona      ES  1519.123333
95                 Kitchener      CA  1490.150000
125              Los Angeles      CL  1418.705000
117               Leeuwarden      NL  1191.510000
9               Antwerp Zuid      BE  1171.856667
71                   Granada      ES  1134.745000
151                    Natal      BR  1114.665000
177  Porto Alegre (2 - 2024)      BR  1073.450000
121             Liège-Oupeye      BE  1038.880000
35              Brussels (2)      BE  1020.470000
207                 Serraria      BR  1016.325000
41             Charleroi-Est      BE  1002.600000
191            Rotterdam (2)      NL   989.586667
128                   Luzern      CH   948.650000
46                Concepción      CL   946.915000

In [37]:
# Charts ausprobieren für Datawrapper

In [104]:
# 0. cot weglassen
df_drugs = df[df["Metabolite"] != "cot"]

# 1. Durchschnitt pro Droge und Land berechnen
country_drug = (
    df_drugs.groupby(["Metabolite", "Country"], as_index=False)
      .agg(
          avg_daily_mean=("Daily mean", "mean"),
          n_sites=("Site ID", "nunique")
      )
)

# 2. Ranking pro Droge berechnen
country_drug["rank"] = (
    country_drug.groupby("Metabolite")["avg_daily_mean"]
    .rank(method="dense", ascending=False)
    .astype(int)
)

# 3. Führendes Land pro Droge
leaders = (
    country_drug.sort_values(["Metabolite", "avg_daily_mean"], ascending=[True, False])
    .groupby("Metabolite")
    .first()
    .reset_index()
    [["Metabolite", "Country", "avg_daily_mean"]]
    .rename(columns={
        "Country": "Leading country",
        "avg_daily_mean": "Top value"
    })
)

# 4. Schweiz-Werte
switzerland = (
    country_drug[country_drug["Country"] == "CH"]
    [["Metabolite", "rank", "avg_daily_mean", "n_sites"]]
    .rename(columns={
        "rank": "Switzerland rank",
        "avg_daily_mean": "Switzerland value",
        "n_sites": "Swiss sites"
    })
)

# 5. Zusammenführen
dw_table = switzerland.merge(leaders, on="Metabolite")

# 6. Anzahl Länder pro Droge hinzufügen
country_counts = (
    country_drug.groupby("Metabolite")["Country"]
    .nunique()
    .reset_index()
    .rename(columns={"Country": "Number of countries"})
)

dw_table = dw_table.merge(country_counts, on="Metabolite")

# 7. Spalten sortieren und runden
dw_table = dw_table[
    [
        "Metabolite",
        "Switzerland rank",
        "Number of countries",
        "Switzerland value",
        "Leading country",
        "Top value",
    ]
]

dw_table["Switzerland value"] = dw_table["Switzerland value"].round(2)
dw_table["Top value"] = dw_table["Top value"].round(2)

# 8. Anzeigen
dw_table.sort_values("Switzerland rank")

,Metabolite,Switzerland rank,Number of countries,Switzerland value,Leading country,Top value
3,cocaine,8,41,612.92,CA,1694.81
5,methamphetamine,12,41,21.43,US,946.83
2,cannabis,13,34,92.77,CA,628.98
0,MDMA,14,40,26.72,NL,123.70
4,ketamine,15,36,20.23,GB,181.05
1,amphetamine,23,39,34.24,NO,345.13

In [105]:
dw_table = dw_table.rename(columns={
    "Metabolite": "Drug",
    "Switzerland rank": "Swiss rank",
    "Number of countries": "Countries analysed",
    "Switzerland value": "Swiss average",
    "Leading country": "Top country",
    "Top value": "Highest average"
})

In [106]:
dw_table.sort_values("Swiss rank")

,Drug,Swiss rank,Countries analysed,Swiss average,Top country,Highest average
3,cocaine,8,41,612.92,CA,1694.81
5,methamphetamine,12,41,21.43,US,946.83
2,cannabis,13,34,92.77,CA,628.98
0,MDMA,14,40,26.72,NL,123.70
4,ketamine,15,36,20.23,GB,181.05
1,amphetamine,23,39,34.24,NO,345.13

In [107]:
dw_table.to_csv("switzerland_drug_ranking_datawrapper.csv", index=False)

In [ ]:
# Wo steht die Schweiz bei Kokain ?

In [54]:
cocaine = (
    df_drugs[df_drugs["Metabolite"] == "cocaine"]
    .groupby("Country")["Daily mean"]
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

cocaine.to_csv("cocaine_country_ranking.csv", index=False)

In [55]:
# Alle schweizer Städte im Vergleich

In [109]:
ch_cocaine = (
    df[
        (df["Country"] == "CH") &
        (df["Metabolite"] == "cocaine")
    ]
    [["City", "Daily mean"]]
    .sort_values("Daily mean", ascending=False)
)

ch_cocaine.to_csv("swiss_cocaine_cities.csv", index=False)

In [58]:
# Party Droge am Wochenende

In [110]:
df["Weekend increase %"] = (
    (df["Weekend mean"] - df["Weekday mean"])
    / df["Weekday mean"]
) * 100

In [112]:
weekend = (
    df[df["Metabolite"].isin(["MDMA", "cocaine", "amphetamine"])]
    .groupby("Metabolite")["Weekend increase %"]
    .mean()
    .reset_index()
)

In [114]:
weekend

    Metabolite  Weekend increase %
0         MDMA          120.056828
1  amphetamine           16.721325
2      cocaine           39.292838

In [116]:
weekend = weekend.rename(columns={
    "Metabolite": "Drug",
    "Weekend increase %": "Increase (%)"
})

In [117]:
weekend.to_csv(
    "weekend_drug_increase.csv",
    index=False
)

In [118]:
# Welche Städte zeigen den stärksten Wochenend-Effekt?

In [120]:
weekend_city = (
    df[
        df["Metabolite"].isin(["MDMA", "cocaine", "amphetamine"])
    ]
    .groupby(["City", "Metabolite"])["Weekend increase %"]
    .mean()
    .reset_index()
)

weekend_city.sort_values(
    "Weekend increase %",
    ascending=False
).head(20)

                    City   Metabolite  Weekend increase %
138           Copenhagen         MDMA          679.583219
426             Montreal  amphetamine          572.204800
710           Whitehorse         MDMA          517.391304
31                 Arlon  amphetamine          453.298153
498   Paris Seine Centre         MDMA          430.733042
318                Kranj  amphetamine          393.147438
30                 Arlon         MDMA          381.950673
367          Los Angeles         MDMA          364.864865
501  Paris South Suburbs         MDMA          353.488372
375               Luzern         MDMA          351.908397
70               Bologna         MDMA          319.474836
699                Växjö         MDMA          284.110669
338             Lausanne         MDMA          281.899006
15            Altenrhein         MDMA          280.163599
128         Christchurch         MDMA          271.069924
9              Agia Napa         MDMA          258.511390
163               Dülmen         MDMA          257.241568
724               Zurich         MDMA          254.598296
495               Paphos         MDMA          245.254470
275                 Kemi         MDMA          239.728116

In [122]:
# Durchschnittlicher Wochenend-Effekt über alle Städte hinweg.

weekend = (
    df[df["Metabolite"].isin(["MDMA", "cocaine", "amphetamine"])]
    .groupby("Metabolite")["Weekend increase %"]
    .mean()
    .reset_index()
    .sort_values("Weekend increase %", ascending=False)
)

In [124]:
weekend

    Metabolite  Weekend increase %
0         MDMA          120.056828
2      cocaine           39.292838
1  amphetamine           16.721325

In [141]:
# Top 5 Städte pro Droge mit den weekendspikes / Which five cities show the strongest weekend spike for each drug?

# Stadtnamen bereinigen
df["City clean"] = (
    df["City"]
    .str.replace(r"\s*\(\d+.*?\)", "", regex=True)
    .str.strip()
)

# Durchschnittlicher Wochenend-Effekt pro Stadt
weekend_city = (
    df.groupby(
        ["Metabolite", "City clean", "Country"],
        as_index=False
    )["Weekend increase %"]
    .mean()
)

# Top 5 Städte pro Droge
top5_weekend = (
    weekend_city
    .sort_values(
        ["Metabolite", "Weekend increase %"],
        ascending=[True, False]
    )
    .groupby("Metabolite")
    .head(5)
)

top5_weekend

           Metabolite          City clean Country  Weekend increase %
46               MDMA          Copenhagen      DK          679.583219
236              MDMA          Whitehorse      CA          517.391304
166              MDMA  Paris Seine Centre      FR          430.733042
10               MDMA               Arlon      BE          381.950673
123              MDMA         Los Angeles      CL          364.864865
381       amphetamine            Montreal      CA          572.204800
254       amphetamine               Arlon      BE          453.298153
346       amphetamine               Kranj      SI          393.147438
395       amphetamine          Novo mesto      SI          195.930640
441       amphetamine            Serraria      BR          126.069690
490          cannabis           Barcelona      ES          581.723784
530          cannabis             Goiânia      BR          231.235211
621          cannabis            São Luis      BR          172.294372
560          cannabis              Lleida      ES          158.664650
523          cannabis             Eleusis      GR           88.606238
787           cocaine            Mytilene      GR          202.439024
864           cocaine         Trollhättan      SE          164.991938
813           cocaine         Pietarsaari      FI          158.435673
862           cocaine               Tartu      EE          153.933480
858           cocaine           Söderhamn      SE          151.335137
922               cot               Mainz      DE           32.119780
891               cot              Athens      GR           28.039047
911               cot        Karlovy Vary      CZ           13.620986
914               cot              Laupen      CH           12.041607
935               cot              Prague      CZ           10.581127
981               ets           Trondheim      NO          140.829949
956               ets              Bergen      NO          121.471424
957               ets          Copenhagen      DK          106.705173
955               ets           Barcelona      ES          102.369189
974               ets                Oslo      NO          102.294296
1056         ketamine        Karlovy Vary      CZ         5125.000000
1152         ketamine          Whitehorse      CA         1754.529617
1110         ketamine               Porto      PT          536.446122
1100         ketamine          Novo mesto      SI          238.131292
1072         ketamine            Limassol      CY          189.640775
1278  methamphetamine          Leeuwarden      NL          785.897436
1164  methamphetamine              Almada      PT          377.306553
1246  methamphetamine          Istanbul I      TR          239.218009
1383  methamphetamine         Trollhättan      SE          228.125000
1236  methamphetamine           Hallstatt      AT          177.319588

In [130]:
#In welcher Schweizer Stadt steigt Kokain, MDMA oder Cannabis am Wochenende am stärksten an? 

ch_weekend = df[df["Country"] == "CH"]

top_weekend_ch = (
    ch_weekend.loc[
        ch_weekend.groupby("Metabolite")["Weekend increase %"].idxmax()
    ][["Metabolite", "City", "Weekend increase %"]]
    .sort_values("Weekend increase %", ascending=False)
)

top_weekend_ch

           Metabolite        City  Weekend increase %
5075             MDMA       Berne          712.401055
4778      amphetamine      Zurich          126.899798
3588         cannabis       Berne          119.889503
2047         ketamine       Berne          110.510949
4225          cocaine       Basel           63.704936
768   methamphetamine  Altenrhein           58.132045
501               cot      Laupen           12.041607

In [65]:
# heatmap Schweiz

In [95]:
df["City"] = df["City"].replace({
    "Zurich (2)": "Zurich",
    "Basel (2)": "Basel"   # falls vorhanden
})

In [96]:
swiss = (
    df[df["Country"] == "CH"]
    .pivot_table(
        index="City",
        columns="Metabolite",
        values="Daily mean",
        aggfunc="mean"
    )
)

In [148]:
swiss.head(20)

Metabolite,MDMA,amphetamine,cannabis,cocaine,cot,ketamine,methamphetamine
City,,,,,,,
Altenrhein,12.720000,50.540000,78.980000,743.470000,971.07,3.090000,8.270000
Basel,19.859231,30.120000,58.314000,515.717692,556.67,18.830000,27.620000
Berne,21.474615,44.885000,65.950000,470.223571,NaN,12.276667,21.370769
Chur,8.620000,25.810000,69.200000,646.620000,1020.66,6.130000,2.920000
Geneva,28.184615,11.447857,189.043333,635.240000,NaN,33.043333,9.733846
Laupen,9.020000,38.350000,37.290000,297.450000,703.87,2.720000,15.870000
Lausanne,31.670000,8.930000,NaN,312.905000,NaN,NaN,3.065000
Lugano,7.487500,0.000000,90.760000,436.537500,820.90,9.860000,0.432500
Luzern,19.720000,65.540000,75.360000,948.650000,874.33,9.960000,6.500000
Neuchatel,10.090000,31.560000,73.330000,377.230000,836.55,16.820000,17.200000
Schwyz,9.130000,74.050000,68.910000,538.550000,1106.92,8.560000,7.410000
Solothurn,17.690000,42.990000,24.340000,762.680000,734.06,6.790000,12.450000
St. Gallen Hofen,28.032000,71.862000,11.770000,893.672000,NaN,NaN,13.087500
Zurich,48.045714,43.782857,116.378333,814.795000,879.90,49.406667,45.411538

In [146]:
swiss.to_csv("swiss_drugs_heatmap.csv")

In [152]:
cocaine_map = swiss[["cocaine"]].reset_index()

cocaine_map

Metabolite              City     cocaine
0                 Altenrhein  743.470000
1                      Basel  515.717692
2                      Berne  470.223571
3                       Chur  646.620000
4                     Geneva  635.240000
5                     Laupen  297.450000
6                   Lausanne  312.905000
7                     Lugano  436.537500
8                     Luzern  948.650000
9                  Neuchatel  377.230000
10                    Schwyz  538.550000
11                 Solothurn  762.680000
12          St. Gallen Hofen  893.672000
13                    Zurich  814.795000

In [154]:
## Koordinaten einsetzen.. 

coords = {
    "Altenrhein": (47.4900, 9.5560),
    "Basel": (47.5596, 7.5886),
    "Berne": (46.9480, 7.4474),
    "Chur": (46.8508, 9.5320),
    "Geneva": (46.2044, 6.1432),
    "Laupen": (46.9020, 7.2390),
    "Lausanne": (46.5197, 6.6323),
    "Lugano": (46.0037, 8.9511),
    "Luzern": (47.0502, 8.3093),
    "Neuchatel": (46.9896, 6.9293),
    "Schwyz": (47.0207, 8.6541),
    "Solothurn": (47.2088, 7.5323),
    "St. Gallen Hofen": (47.4245, 9.3767),
    "Zurich": (47.3769, 8.5417),
}

cocaine_map["lat"] = cocaine_map["City"].map(lambda x: coords[x][0])
cocaine_map["lon"] = cocaine_map["City"].map(lambda x: coords[x][1])

cocaine_map

Metabolite              City     cocaine      lat     lon
0                 Altenrhein  743.470000  47.4900  9.5560
1                      Basel  515.717692  47.5596  7.5886
2                      Berne  470.223571  46.9480  7.4474
3                       Chur  646.620000  46.8508  9.5320
4                     Geneva  635.240000  46.2044  6.1432
5                     Laupen  297.450000  46.9020  7.2390
6                   Lausanne  312.905000  46.5197  6.6323
7                     Lugano  436.537500  46.0037  8.9511
8                     Luzern  948.650000  47.0502  8.3093
9                  Neuchatel  377.230000  46.9896  6.9293
10                    Schwyz  538.550000  47.0207  8.6541
11                 Solothurn  762.680000  47.2088  7.5323
12          St. Gallen Hofen  893.672000  47.4245  9.3767
13                    Zurich  814.795000  47.3769  8.5417

In [155]:
cocaine_map.to_csv("swiss_cocaine_map.csv", index=False)